name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.9
  firebase_analytics: ^10.8.9
  provider: ^6.1.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  toast: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets: 
    - images/logo.jpg