// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2kpipu8KNpskIWGN8MnjENQ9xCzx21p0',
    appId: '1:875578923612:web:969c4dc3dc106ecece2499',
    messagingSenderId: '875578923612',
    projectId: 'restarauntnigmatov',
    authDomain: 'restarauntnigmatov.firebaseapp.com',
    storageBucket: 'restarauntnigmatov.appspot.com',
    measurementId: 'G-ZG0BKSX1B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANtkoPiT_tKcqzCVWPsAVnR2_0ntZr2mc',
    appId: '1:875578923612:android:eab4d056f1a1f074ce2499',
    messagingSenderId: '875578923612',
    projectId: 'restarauntnigmatov',
    storageBucket: 'restarauntnigmatov.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0csVuCecdZz73MusqDD68nj7u5yKU2o',
    appId: '1:875578923612:ios:f172263f6d9f4c36ce2499',
    messagingSenderId: '875578923612',
    projectId: 'restarauntnigmatov',
    storageBucket: 'restarauntnigmatov.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0csVuCecdZz73MusqDD68nj7u5yKU2o',
    appId: '1:875578923612:ios:dfb1a933edec68f3ce2499',
    messagingSenderId: '875578923612',
    projectId: 'restarauntnigmatov',
    storageBucket: 'restarauntnigmatov.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
